import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import SideBar from './SideBar'
import LoginBtn from '../login-button'
import Modal from './ModalComp/Modal'
import AppContext from '../../context/TwitterContext'
import { ITweetEditorProps, ITwitterContext } from '../../types'
import { curryTweetEditor } from '../TweetEditor'
import { ITweetFileAttachments } from '../../models/Tweet'

export default function Layout({children} : {children : React.ReactNode}){
  const router = useRouter()
  const pathName = router.pathname
  const {modal} = router.query 
  const {modalOn,openModal,closeModal} = useContext(AppContext) as ITwitterContext

  const [tweetText_,setTweetText_] = useState<string>("Hello guys!")
  const [tweetAttachments_,setTweetAttachments_] = useState<ITweetFileAttachments>({content_type:""})

  useEffect(()=>{
    //console.log("Layout Modal :", modal,modal === " tweet")
    if(modal === "tweet"){
      const tweetEditorProps : ITweetEditorProps = {motive:"tweet",tweetText:tweetText_,setTweetText:setTweetText_,tweetAttachments:tweetAttachments_,setTweetAttachments:setTweetAttachments_}
      openModal({title:"",url:"/component/tweet",parameters:tweetEditorProps  ,type:"tweet"})
    }else{
      closeModal({goBack:false})
    }
  },[modal])
  const get_title = (pathName : String)=>{
    let title : String;
    switch(pathName){
        case "/home":
            title = "Home/Twitter"
        case "/explore":
            title = "Explore/Twitter"
        // case "/":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        default:
        title = 'Twitter'
    }
    return title
  }
  return(
    <>
      <Head>
        <title>{`${get_title(pathName)}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <main id="desktop_layout">
          <div className={`grid  mx-auto grid-flow-col h-screen w-fit relative`}>
            <SideBar/>
            <div className=' shadow-md w-fit'>
              {children}
            </div>
            <div className='sticky inset-y-0 right-0'  style={{width:"350px"}}>
                <LoginBtn />
            </div>
          </div>
          <Modal />
      </main>
    </>
  )
}