import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import SideBar from './SideBar'
import LoginBtn from '../login-button'
import Modal from './ModalComp/Modal'
import AppContext from '../../context/TwitterContext'
import { ITwitterContext } from '../../types'
import { curryTweetEditor } from '../TweetEditor'

export default function Layout({children} : {children : React.ReactNode}){
  const router = useRouter()
  const pathName = router.pathname
  const {modal} = router.query 
  const {modalOn,openModal,closeModal} = useContext(AppContext) as ITwitterContext
  useEffect(()=>{
    //console.log(modal,modal === " tweet")
    if(modal === "tweet" && !modalOn){
      openModal({title:"",url:"/component/tweet",parameters:{motive:"tweet"},type:"tweet"})
    }
    if(modal === "add_username" && !modalOn){
      openModal({title:"",url:"/i/flow/username",parameters:{motive:"tweet"},type:"add_username"})
    }
    if(!modal && modalOn){
      closeModal({goBack:false})
    }
  },[modal,modalOn])
  const get_title = (pathName : String)=>{
    let title : String;
    switch(pathName){
        case "/home":
            title = "Home/Twitter"
        case "/explore":
            title = "Explore/Twitter"
        // case "/":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        default:
        title = 'Twitter'
    }
    return title
  }
  return(
    <>
      <Head>
        <title>{`${get_title(pathName)}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <main id="desktop_layout">
          <div className='grid  mx-auto grid-flow-col  h-screen w-fit'>
            <SideBar/>
            <div className=' shadow-md' style={{width:"580px"}}>
              {children}
            </div>
            <div className=''  style={{width:"350px"}}>
                <LoginBtn />
            </div>
          </div>
          {modalOn && <Modal />}
      </main>
      
    </>
  )
}