import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import SideBar from './SideBar'
import LoginBtn from '../login-button'

export default function Layout({children} : {children : React.ReactNode}){
  const router = useRouter().pathname
  const get_title = (router:String)=>{
    let title : String;
    switch(router){
        case "/home":
            title = "Home/Twitter"
        case "/explore":
            title = "Explore/Twitter"
        // case "/":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        // case "/Home":
        //     title = "Home/Twitter"
        default:
        title = 'Twitter'
    }
    return title
  }
  return(
    <>
      <Head>
        <title>{`${get_title(router)}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <main>
          <div className='grid  mx-auto grid-flow-col auto-cols-max h-screen w-fit'>
            <SideBar/>
            <div className='bg-slate-300 ' style={{width:"598px"}}>
              {children}
            </div>
            <div className='bg-slate-100 '  style={{width:"350px"}}>
                <LoginBtn />
            </div>
          </div>
      </main>
      
    </>
  )
}